name: user-statistician

on:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate the user stats image
        uses: cicirello/user-statistician@v1
        with:
          colors: dark
          max-languages: 10
          animated-language-chart: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
